//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spindle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spindle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player is not currently arrested..
        /// </summary>
        internal static string EndArrestPlayerNotArrested {
            get {
                return ResourceManager.GetString("EndArrestPlayerNotArrested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL scheme must be http or https..
        /// </summary>
        internal static string ExceptionBrowserRequestNotHttp {
            get {
                return ResourceManager.GetString("ExceptionBrowserRequestNotHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component {0} could not be found on {1}..
        /// </summary>
        internal static string ExceptionComponentNotFound {
            get {
                return ResourceManager.GetString("ExceptionComponentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter types can only have one generic argument and it must be the value type being translated..
        /// </summary>
        internal static string ExceptionConverterInvalidGenericType {
            get {
                return ResourceManager.GetString("ExceptionConverterInvalidGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be a non-empty string..
        /// </summary>
        internal static string ExceptionEmptyString {
            get {
                return ResourceManager.GetString("ExceptionEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum converters can not be added later. Use SetEnumStringConverter instead..
        /// </summary>
        internal static string ExceptionEnumConverterNotValid {
            get {
                return ResourceManager.GetString("ExceptionEnumConverterNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature can only be used when on the main thread..
        /// </summary>
        internal static string ExceptionGameThread {
            get {
                return ResourceManager.GetString("ExceptionGameThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be used when on the main thread..
        /// </summary>
        internal static string ExceptionGameThreadContext {
            get {
                return ResourceManager.GetString("ExceptionGameThreadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected underlying type for enum type {0}..
        /// </summary>
        internal static string ExceptionInvalidEnumType {
            get {
                return ResourceManager.GetString("ExceptionInvalidEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string either has extra formatting arguments or is using an inforrect format string syntax..
        /// </summary>
        internal static string ExceptionInvalidFormat {
            get {
                return ResourceManager.GetString("ExceptionInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings sent to clients can not exceed 2048 characters..
        /// </summary>
        internal static string ExceptionNetStringTooLong {
            get {
                return ResourceManager.GetString("ExceptionNetStringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No non-alt player spawns available..
        /// </summary>
        internal static string ExceptionNoPlayerSpawnsAvailable {
            get {
                return ResourceManager.GetString("ExceptionNoPlayerSpawnsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be a non-abstract subclass of TranslationCollection with a parameterless constructor..
        /// </summary>
        internal static string ExceptionNotValidTranslationCollectionType {
            get {
                return ResourceManager.GetString("ExceptionNotValidTranslationCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player not online: {0}..
        /// </summary>
        internal static string ExceptionPlayerOffline {
            get {
                return ResourceManager.GetString("ExceptionPlayerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin is misconfigured..
        /// </summary>
        internal static string ExceptionSpindlePluginSettingsException {
            get {
                return ResourceManager.GetString("ExceptionSpindlePluginSettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value given for LoadTime ({0}) is out of range for SpindlePluginLoadTime..
        /// </summary>
        internal static string ExceptionSpindlePluginSettingsException_LoadTime {
            get {
                return ResourceManager.GetString("ExceptionSpindlePluginSettingsException_LoadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam ID must belong to a Game Server..
        /// </summary>
        internal static string ExceptionSteamIdNotGameServer {
            get {
                return ResourceManager.GetString("ExceptionSteamIdNotGameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam ID must belong to an Individual account type..
        /// </summary>
        internal static string ExceptionSteamIdNotIndividual {
            get {
                return ResourceManager.GetString("ExceptionSteamIdNotIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in callback dispatched on main thread. See stack trace below..
        /// </summary>
        internal static string GameThreadDispatchExceptionCurrent {
            get {
                return ResourceManager.GetString("GameThreadDispatchExceptionCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in callback dispatched to main thread. See stack trace below..
        /// </summary>
        internal static string GameThreadDispatchExceptionNotCurrent {
            get {
                return ResourceManager.GetString("GameThreadDispatchExceptionNotCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Languages.json or Languages.yml file..
        /// </summary>
        internal static string LanguageFileNotFound {
            get {
                return ResourceManager.GetString("LanguageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is a required property for Language..
        /// </summary>
        internal static string LanguageParse_DisplayNameRequired {
            get {
                return ResourceManager.GetString("LanguageParse_DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName is a required property for Language..
        /// </summary>
        internal static string LanguageParse_NameRequired {
            get {
                return ResourceManager.GetString("LanguageParse_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player component {0} did not assign the Player property to the expected player..
        /// </summary>
        internal static string LogPlayerComponentFailedToAssignPlayerProperty {
            get {
                return ResourceManager.GetString("LogPlayerComponentFailedToAssignPlayerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor for player component {0} threw an exception for player {1}..
        /// </summary>
        internal static string LogPlayerComponentFailedToCreate {
            get {
                return ResourceManager.GetString("LogPlayerComponentFailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player component {0} threw an exception trying to dispose on player {1}..
        /// </summary>
        internal static string LogPlayerComponentFailedToDispose {
            get {
                return ResourceManager.GetString("LogPlayerComponentFailedToDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize method for player component {0} threw an exception for player {1}..
        /// </summary>
        internal static string LogPlayerComponentFailedToInitialize {
            get {
                return ResourceManager.GetString("LogPlayerComponentFailedToInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had to fallback during UnturnedAssets initialization: failed to find field {0}..
        /// </summary>
        internal static string LogUnturnedAssetsFieldNotFound {
            get {
                return ResourceManager.GetString("LogUnturnedAssetsFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had to fallback during UnturnedAssets initialization..
        /// </summary>
        internal static string LogUnturnedAssetsGenericError {
            get {
                return ResourceManager.GetString("LogUnturnedAssetsGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had to fallback during UnturnedAssets initialization: failed to find type {0}..
        /// </summary>
        internal static string LogUnturnedAssetsTypeNotFound {
            get {
                return ResourceManager.GetString("LogUnturnedAssetsTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create getter for field {0} during UnturnedAssets initialization. Assets loaded after startup may not stay in sync..
        /// </summary>
        internal static string LogUnturnedAssetsVersionFieldFailed {
            get {
                return ResourceManager.GetString("LogUnturnedAssetsVersionFieldFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find field {0} during UnturnedAssets initialization. Assets loaded after startup may not stay in sync..
        /// </summary>
        internal static string LogUnturnedAssetsVersionFieldNotFound {
            get {
                return ResourceManager.GetString("LogUnturnedAssetsVersionFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy request for {0} was cancelled by a CancellationToken..
        /// </summary>
        internal static string PlayerSpyOperation_Cancelled {
            get {
                return ResourceManager.GetString("PlayerSpyOperation_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy request for {0} cancelled after the player disconnected..
        /// </summary>
        internal static string PlayerSpyOperation_Disconnected {
            get {
                return ResourceManager.GetString("PlayerSpyOperation_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy request for {0} timed out after {1}..
        /// </summary>
        internal static string PlayerSpyOperation_Timeout {
            get {
                return ResourceManager.GetString("PlayerSpyOperation_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array not long enough for {0} elements..
        /// </summary>
        internal static string SharedTranslationDictionary_ArrayTooShort {
            get {
                return ResourceManager.GetString("SharedTranslationDictionary_ArrayTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language codes are mismatched..
        /// </summary>
        internal static string SharedTranslationDictionary_LanguageCodesMismatched {
            get {
                return ResourceManager.GetString("SharedTranslationDictionary_LanguageCodesMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting Spindle..
        /// </summary>
        internal static string SpindleLaunchException {
            get {
                return ResourceManager.GetString("SpindleLaunchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error shutting Spindle down..
        /// </summary>
        internal static string SpindleShutdownException {
            get {
                return ResourceManager.GetString("SpindleShutdownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting argument at index {0} is not a type compatable with it&apos;s generic type!.
        /// </summary>
        internal static string TranslateUnsafe_FormattingArgumentMismatch {
            get {
                return ResourceManager.GetString("TranslateUnsafe_FormattingArgumentMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting argument at index {0} is null and its generic type is a value type!.
        /// </summary>
        internal static string TranslateUnsafe_FormattingArgumentMismatchValueTypeNull {
            get {
                return ResourceManager.GetString("TranslateUnsafe_FormattingArgumentMismatchValueTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This represents a generic name of the set of values..
        /// </summary>
        internal static string TranslationsEnumNameDescription {
            get {
                return ResourceManager.GetString("TranslationsEnumNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniTask injection was already completed by another module, likely OpenMod..
        /// </summary>
        internal static string UniTaskInjectionHandledByOtherModule {
            get {
                return ResourceManager.GetString("UniTaskInjectionHandledByOtherModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize UniTask, check that the version of UniTask.dll is up to date and try redownloading it. Do NOT get it from NuGet, as that verison is not for Unity..
        /// </summary>
        internal static string UniTaskInjectionReflectionFailure {
            get {
                return ResourceManager.GetString("UniTaskInjectionReflectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniTask injection completed successfully by Spindle..
        /// </summary>
        internal static string UniTaskInjectionSuccess {
            get {
                return ResourceManager.GetString("UniTaskInjectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniTask exception not handled correctly..
        /// </summary>
        internal static string UniTaskUnobservedException {
            get {
                return ResourceManager.GetString("UniTaskUnobservedException", resourceCulture);
            }
        }
    }
}
